### ISSUE TITLE
gont:municipality is not defined

### ISSUE THREAD

**Issue by ktk** [gontch/gont.ch-site#1]
`gont:municipality` seems missing in the schema

**Comment by retog** [comment]
Please helpt me specify it,  I assume it's a property with range :Municipality. On which types is it applied (i.e. what is its domain)? Usage example?

**Comment by retog** [comment]
Talking with @ktk : It is used to point from historised to the non-historiesed municipality but the domain should be broader to allow for other entities to point to a municipality.

**Comment by ktk** [comment]
Not deployed yet it seems, reopening.

**Comment by retog** [comment]
created https://github.com/gontch/gont.ch-site/issues/8 to ensure seployment.
