### ISSUE TITLE
Entry page most times returns 404

### ISSUE THREAD

**Issue by retog** [gontch/gont.ch-site#10]
It happens most times but not always (as shown in screenshot).

![2016-12-05-164009_3840x2160_scrot](https://cloud.githubusercontent.com/assets/110756/20891270/45653360-bb0a-11e6-872a-4edc75051709.png)

**Comment by retog** [comment]
After getting 404 in various browsers on several devices, after I started observing the requests I'm no longer getting them!

That's how a request arriving to trifid looks like:
```
GET / HTTP/1.1
Host: gont.ch
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/53.0.2785.143 Chrome/53.0.2785.143 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Language: en-US,en;q=0.8,de;q=0.6
X-Forwarded-For: 172.19.0.10
x-forwarded-proto: https
X-Forwarded-Port: 443
Accept-Encoding: gzip
X-Varnish: 590168
```

**Comment by retog** [comment]
After making a request to `http://gont.ch/` which correctly gets a 404 answer I'm getting again 404 answers on `https://gont.ch/` without the trifid docker getting the requests.

@ktk, do you think varnish is mixing up the cache of `https://gont.ch` and `http://gont.ch`?

**Comment by ktk** [comment]
@retog might be, will check that once I got all the updated services working.

**Comment by retog** [comment]
Obsoleted by the resolution of #11
